### ISSUE TITLE
Add ref to figure + inter section refs

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/engineering-shiny-book#111]
`\@ref(fig:apptree) `

`\@ref(section-name)`

**Comment by statnmap** [comment]
You can also add markdown legends to figure.
Here a reprex with:

- Reference to a named chunk with a figure: ` \@ref(fig:planning-ahead-1)`
- Legend with a reference. text written in markdown: `(ref:apptreecap)`
- Reference to the referenced legend in tha chunk option ` fig.cap='(ref:apptreecap)' `

Do not forget empty lines.  

```
---
title: "Untitled"
author: "Sébastien Rochette"
date: "10/02/2020"
output: bookdown::html_document2
---

## Including Plots

You can also embed plots, for example in Fig. \@ref(fig:planning-ahead-1):

(ref:apptreecap) Representation of a **Shiny app** as a tree of modules and submodules

` ``{r planning-ahead-1, echo=FALSE, fig.cap='(ref:apptreecap)'}
plot(pressure)
` ``

```
