### ISSUE TITLE
Give a little more context about what an R6 class is.

### ISSUE THREAD

**Issue by jcrodriguez1989** [ThinkR-open/engineering-shiny-book#183]
I think the book would be easily readable for new Shiny users, so I would suggest adding references to R6 class documentations (as it is not broadly used by the R community).
In chapters 3 and 10, `R6` is mentioned, maybe you could add a reference to "Advanced R"'s R6 chapter.
And also in chapter 16, where you have the `16.1.4 Using R6 as a data storage` chapter, I think something like "R6 objects have the particularity that if inside a function, any of their slots are modified, they keep changes even outside the function. An extended description of the R6 class can be found at the R6 chapter of the Advanced R book https://adv-r.hadley.nz/r6.html".

**Comment by ColinFay** [comment]
Thanks for the suggestion! This had been added.
