### ISSUE TITLE
Warn about memoization of random behaviour functions.

### ISSUE THREAD

**Issue by jcrodriguez1989** [ThinkR-open/engineering-shiny-book#184]
In section "17.2 Caching elements" I think it's giving too much emphasis on memoization of functions. I think it would be good to add a sentence about warning that memoization is good only for non-random functions. Mostly, for non-experienced users. Something like "Just take special attention when caching functions, the expected output should not vary given the same input.".

**Comment by ColinFay** [comment]
Added, thanks!
