### ISSUE TITLE
Two incomplete sentences in chapter 9

### ISSUE THREAD

**Issue by rpodcast** [ThinkR-open/engineering-shiny-book#197]
I was brushing up on chapter 9 (Setting up for success with `{golem}`) and noticed a couple of sentences that seemed to be incomplete.  I wasn't sure how they should have been ended, or I would have proposed something myself.  Here they are:

https://github.com/ThinkR-open/engineering-shiny-book/blob/8ecf864fb77bc8dbabafab0582269f2b985fc3a8/09-step-by-step-prototype.Rmd#L68-L70

https://github.com/ThinkR-open/engineering-shiny-book/blob/8ecf864fb77bc8dbabafab0582269f2b985fc3a8/09-step-by-step-prototype.Rmd#L168-L170

I am so thrilled with how this book has come together.  I shared it during my day job's internal Shiny forum and everyone was very impressed 👍

**Comment by ColinFay** [comment]
Thanks!
