### ISSUE TITLE
Potential edits for Chapter 1

### ISSUE THREAD

**Issue by davidpb90** [ThinkR-open/engineering-shiny-book#203]
Hi, I fixed some typos in Chapter 1 (with a typo in the commit message ironically ^^), but there are 3 details that could be edited but are either not necessarily wrong or you need to decide how to change them:

Line 81: In the end of the line: either designing interfaces or an interface.
Line 102: Probably not an error, but I think 'start and end date' is much more common than 'starting' and 'ending', and that's how you use it in the sentence thereafter. In that sentence probably 'date' should be added after 'end', for the sake of consistency.

**Comment by ColinFay** [comment]
Thanks for the feedback!
