### ISSUE TITLE
Typo: Ch 16.2.2

### ISSUE THREAD

**Issue by bstrain71** [ThinkR-open/engineering-shiny-book#212]
"300 mo of data"

Should read

"300MB of data"

https://github.com/ThinkR-open/engineering-shiny-book/blob/d9964a6dd03c04fdf9b73ce7ec3cf2e6b70c9456/16-common-app-caveats.Rmd#L604

**Comment by ColinFay** [comment]
Just leaving it as a comment for all the issues you've open correcting the typos: thank you very, very much.
