### ISSUE TITLE
Ch 16.3.3 Typos #2 and #3

### ISSUE THREAD

**Issue by bstrain71** [ThinkR-open/engineering-shiny-book#214]
Typo 1: Singular "database" used when it should be plural "databases"

Typo 2: I think you meant "database**s** are **wildely** used..." not "database are **wildly** used..."

I would say that in practice they are both wildly used and widely used :)
However, you use "widely" on the next line, so I think you meant to say widely not wildly.

https://github.com/ThinkR-open/engineering-shiny-book/blob/d9964a6dd03c04fdf9b73ce7ec3cf2e6b70c9456/16-common-app-caveats.Rmd#L661

**Comment by ColinFay** [comment]
Thank you!!
