### ISSUE TITLE
Ch 17.2.3 Typo

### ISSUE THREAD

**Issue by bstrain71** [ThinkR-open/engineering-shiny-book#217]
"removed" is past tense when it should be present tense to match the rest of the sentence.

This line should be:

"...it might be interesting to periodically **remove**..."

https://github.com/ThinkR-open/engineering-shiny-book/blob/d9964a6dd03c04fdf9b73ce7ec3cf2e6b70c9456/17-optimizing-shiny-code.Rmd#L248

**Comment by ColinFay** [comment]
thanks!
