### ISSUE TITLE
Ch 16.1.1 Grammar

### ISSUE THREAD

**Issue by bstrain71** [ThinkR-open/engineering-shiny-book#220]
"...where too **much** things happen...updated way more often than they should..."

Should be

"...where too **many** things happen...updated way more often than they should **be**..."

https://github.com/ThinkR-open/engineering-shiny-book/blob/d9964a6dd03c04fdf9b73ce7ec3cf2e6b70c9456/16-common-app-caveats.Rmd#L9

**Comment by ColinFay** [comment]
thank you so much!
