### ISSUE TITLE
Typo in 'Introduction': being serveD to gazillions of users

### ISSUE THREAD

**Issue by fBedecarrats** [ThinkR-open/engineering-shiny-book#238]
Many thanks for this great framework, package and book.
Just to report a typo in the [Introduction](https://engineering-shiny.org/index.html): 
> "being in production doesn’t necessarily mean being **serve to** gazillions of users"   

should read: 
> "being in production doesn’t necessarily mean being **served to** gazillions of users"

**Comment by ColinFay** [comment]
Thank you!
