### ISSUE TITLE
Change upper case in chap. 6: Accessibility > accessibility

### ISSUE THREAD

**Issue by fBedecarrats** [ThinkR-open/engineering-shiny-book#239]
Many thanks (again) for this great framework, package and book.
Just to report a tiny typo in the [Chapter 6](https://engineering-shiny.org/matters.html): 
> you will be introduced to web **A**ccessibility very early.

should read: 
> you will be introduced to web **a**ccessibility very early.

**Comment by ColinFay** [comment]
Thanks, corrected !
