### ISSUE TITLE
Harmonize character case in chapter titles

### ISSUE THREAD

**Issue by mayeulk** [ThinkR-open/engineering-shiny-book#286]
Consistency in the case of titles (upper case/lower case) should be improved, e.g.:

Chapter 3 Structuring your Project
Chapter 5 The workflow    >   The **W**orkflow

Chapter 1 About Successful {shiny} Apps
Chapter 10 Building the app with {golem}   >  the **A**pp...

**Comment by ColinFay** [comment]
Hey, 

Thanks for the feedback. 

I just finished integrating the last round of proof-reading from the publisher, and I've taken into account how they chose to build the title, so it should be good by now :) 

Thanks again, 
Colin
