### ISSUE TITLE
Broken links in references

### ISSUE THREAD

**Issue by mayeulk** [ThinkR-open/engineering-shiny-book#287]
For shinyalert, there are two URLs being referenced but they get glue in the wrong way as a single URL:
https://github.com/daattali/shinyalert%0Ahttps://daattali.com/shiny/shinyalert-demo/

These URLs fail, too, in the list of references:
https://doi.org/10.18129/B9.bioc.spatialLIBD
http://git.mango.local/gcsardi/packageMetrics2

**Comment by ColinFay** [comment]
Thanks @mayeulk! 

These are automatically generated based on the package information. 

I've changed the entry manually for these inside the .bib, but these were generated from the package doc, so this might be an issue to report on these packages repo :) 

Thanks again,

Colin
