### ISSUE TITLE
Async shiny module - potential example in the book

### ISSUE THREAD

**Issue by Denis-Abdullin** [ThinkR-open/engineering-shiny-book#358]
Hello Everyone,

When implementing inner-session asyncronity within a shiny module (rather creating a module that can be integrated within the app while still keeping the app async) I found out that it doesn't work, unless I print the reactive value result (head or class or smth).  

**Related to:**
https://github.com/ThinkR-open/engineering-shiny-book/blob/master/16-optimizing-shiny-code.Rmd#L541

**App + module**
https://github.com/Denis-Abdullin/async_shiny/blob/main/one_file_app.R

specifically talking about this, I guess "hack"
https://github.com/Denis-Abdullin/async_shiny/blob/main/one_file_app.R#L136

Could this be a potential **example in the book**?

Thanks in advance!
Denis

**Comment by ColinFay** [comment]
Hey,

Yes, when you launch your app, every render function needs to have a return value. If it doesn't, it waits. That's what this comment means: https://github.com/ThinkR-open/engineering-shiny-book/blob/master/16-optimizing-shiny-code.Rmd#L732 

But that might need to be made clearer in the text, thanks for pointing this out, will try to rework this part soon

**Comment by Denis-Abdullin** [comment]
Hey Colin,
Thanks for quick reply and explanation!
My bad - I missed this piece.

Denis
