### ISSUE TITLE
Add content about logging things

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/engineering-shiny-book#48]
One important thing about successful Shiny apps is being able to log what happens in the app, while developing and while in production. 

I think we should have a chapter about: 
- Setting conventions for logging 
- Tooling 

Tools: 
- `{whereami}` by @yonicd
- `{logger}` by @daroczig 
- `{ShinyEventLogger}` by @kalimu

**Comment by daroczig** [comment]
Thanks for the mention :bowing_man: 

Regarding `logger`, I think besides the traditional logging features (that are also very important in Shiny apps), mentioning `log_shiny_input_changes` might be interesting for this topic: https://github.com/daroczig/logger/pull/25
