### ISSUE TITLE
Create authors bio 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/engineering-shiny-book#7]
https://github.com/ThinkR-open/building-shiny-apps-workflow/blob/master/index.Rmd#L34

**Comment by ColinFay** [comment]
@VincentGuyader @Cervangirard @statnmap can you please add your bio in this issue? 

thanks

**Comment by statnmap** [comment]
How long ?
Otherwise, I have this one: 
```
Sébastien is a data scientist at ThinkR, where he teaches anything R related from beginner to expert level, guides R developers towards implementation of best practices, and creates tailor-made R solutions for the needs of his customers.
```

**Comment by ColinFay** [comment]
Perfect, thanks!

**Comment by VincentGuyader** [comment]
un truc comme ca ?

ThinkR Founder, with more than 10 years of experience, and with a
scientific and technical background, Vincent is an R-enthusiast.
He still has his hands in the code, whether to develop applications,
analyze data or build packages. When he’s not coding, he plays with Docker
and manages servers.
Meeting highly technical challenges is not incompatible with pedagogy: he
passionately trains very diverse learner profiles at R.

Vincent Guyader - Statisticien
06.23.83.10.61

**Comment by ColinFay** [comment]
thanks!
