### ISSUE TITLE
Active vs. passive voice in writing style

### ISSUE THREAD

**Issue by eroten** [ThinkR-open/engineering-shiny-book#93]
After reviewing chapter 1, I noticed that the writing style uses a lot of passive voice. Changing to active voice will increase the writing's strength and come off as more professional. Using "of" too often is a big indicator of passive voice. I think this distinction between active and passive voice can really improve the book's tone. 

I want to be clear that I don't mean to patronize! English is a ridiculous language, particularly grammar-wise. 😄 

Here are a few resources for active/passive voice. 
- [Grammarly Active vs. Passive Voice](https://www.grammarly.com/blog/active-vs-passive-voice/)  
- [Purdue OWL explanation](https://owl.purdue.edu/owl/general_writing/academic_writing/active_and_passive_voice/active_versus_passive_voice.html)

**Comment by ColinFay** [comment]
Thanks @eroten for you help! As said in the PR, we are not native speakers so getting this kind of help is very valuable (even more as it's definitely rarer to get writing/style advices than technical advices). 

So thank for pointing that. Will definitely keep that in mind for future writing and when rewording the written chapter :)
